name: Main

on: [push]

jobs:
  sast_scan:
    name: SAST Bandit Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install Bandit
        run: |
          python -m pip install --upgrade pip
          pip install bandit

      - name: Run Bandit Scan
        run: |
          bandit -ll -ii -r . -f json -o bandit-report.json

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: bandit-findings
          path: bandit-report.json

  image_scan:
    name: Build Image and Run Image Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker-practice/actions-setup-docker@v1

      - name: Build Docker Image
        run: docker build -f Dockerfile -t myapp:latest .

      - name: Create default daemon.json if missing
        run: |
          if [ ! -f /etc/docker/daemon.json ]; then
            echo '{}' | sudo tee /etc/docker/daemon.json > /dev/null
            sudo chmod 644 /etc/docker/daemon.json
          fi

      # - name: Show default daemon json content
      #   run: |
      #     if [ -f /etc/docker/daemon.json ]; then
      #       sudo cat /etc/docker/daemon.json
      #     else
      #       echo "/etc/docker/daemon.json does not exist."
      #     fi
      #   continue-on-error: true

      - name: Docker Scout Scan
        run: |
          curl -fsSL https://raw.githubusercontent.com/docker/scout-cli/main/install.sh -o install-scout.sh
          sh install-scout.sh
          echo ${{ secrets.DCKR_PWD }} | docker login -u ${{ secrets.DCKR_USR }} --password-stdin
          docker scout quickview
          docker scout cves
